language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: THREADING="openmp"

    # clang
    - os: osx
      osx_image: xcode11.3
      compiler: clang

    # gcc
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      before_install:
        - rm -rf /usr/local/include/c++
        - brew update
        - brew install gcc && export CC=gcc-7 && export CXX=g++-7
        - THREADING="openmp"

env:
  - OMP_NUM_THREADS=4

before_script:
  - mkdir build
  - cd build

script:
  # installation
  - cmake ..
  - make -j2 VERBOSE=1
  # test simple c++ examples
  - cd examples && ./basic_lib_example1 && ./basic_lib_example2 && ./basic_lib_example3 && ./exampleForCustomHComputation
